import TopCards from '@/components/TopCards';
import Layout from '@/layouts';
import Head from 'next/head';

export default function Dashboard() {
	return (
		<>
			<Head>
				<title>FTY WEB APP</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<TopCards />
			</Layout>
		</>
	);
}
