import { Inter } from 'next/font/google';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const router = useRouter();
	const handleSubmit = (e: any) => {
		e.preventDefault();
		router.push('/admin/dashboard');
	};
	return (
		<>
			<Head>
				<title>FTY WEB APP</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='flex flex-col items-center justify-center min-h-screen mx-auto bg-gray-800'>
				<div className='relative flex flex-col p-5 sm:p-10 sm:bg-white  rounded-3xl sm:w-2/4 lg:w-3/6 xl:w-2/6 sm:shadow space-y-10  '>
					<h1 className='text-xl font-bold text-slate-50 sm:text-black sm:text-3xl '>
						Login to continue
					</h1>
					<form
						onSubmit={handleSubmit}
						className='mt-5 flex p-2.5 flex-col gap-10'>
						<div className='flex flex-1 flex-col space-y-3'>
							<label
								htmlFor='email'
								className='text-xs text-gray-300 sm:text-gray-500 uppercase font-medium px-2.5 '>
								Email
							</label>
							<input
								type='email'
								placeholder='Enter Email'
								className='rounded-md h-12 bg-gray-400 flex-grow  px-5 focus:outline-pink-400 focus:border-pink-200'
							/>
						</div>

						<div className='flex flex-1 flex-col space-y-3'>
							<label
								htmlFor='password'
								className='text-xs text-gray-300  sm:text-gray-500 uppercase font-medium px-2.5 '>
								password
							</label>
							<input
								type='password'
								placeholder='Enter password'
								className='rounded-md h-12 bg-gray-400 flex-grow  px-5 focus:outline-pink-400 focus:border-pink-200'
							/>
							<span className='self-end pt-1'>
								<Link
									href='/'
									as='p'
									className='text-slate-50 sm:sm:text-black text-sm sm:text-base font-semibold '>
									Forgot password ?
								</Link>
							</span>
						</div>

						<button
							type='submit'
							className='bg-pink-400 rounded-md focus:outline-transparent h-12 sm:h-14 cursor-pointer text-lg sm:text-2xl text-white font-semibold hover:-translate-y-1 transition-all duration-150 ease-out'>
							Log in
						</button>
					</form>
				</div>
			</div>
		</>
	);
}
